# Generated by Django 5.0 on 2023-12-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='server', max_length=20, verbose_name='Position'),
        ),
    ]
